behaviors:
  CatcherAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 10000

environment_parameters:
  target_count:
    curriculum:
      - name: Stage1
        completion_criteria:
          measure: reward
          behavior: CatcherAgent
          min_lesson_length: 1000
          signal_smoothing: false
          threshold: 4.2
        value: 1
      - name: Stage2
        completion_criteria:
          measure: reward
          behavior: CatcherAgent
          min_lesson_length: 3000
          signal_smoothing: false
          threshold: 7.2
        value: 2
      - name: Stage3
        value: 4

  targets_moving:
    curriculum:
      - name: Stage1
        completion_criteria:
          measure: reward
          behavior: CatcherAgent
          min_lesson_length: 1000
          signal_smoothing: false
          threshold: 4.2
        value: 0
      - name: Stage2
        completion_criteria:
          measure: reward
          behavior: CatcherAgent
          min_lesson_length: 3000
          signal_smoothing: false
          threshold: 7.2
        value: 1
      - name: Stage3
        value: 1

  use_advanced:
    curriculum:
      - name: Stage1
        completion_criteria:
          measure: reward
          behavior: CatcherAgent
          min_lesson_length: 1000
          signal_smoothing: false
          threshold: 4.2
        value: 0
      - name: Stage2
        completion_criteria:
          measure: reward
          behavior: CatcherAgent
          min_lesson_length: 3000
          signal_smoothing: false
          threshold: 7.2
        value: 0
      - name: Stage3
        value: 1
