behaviors:
  HunterBehavior:
    trainer_type: ppo
    max_steps: 5e5
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    hyperparameters:
      batch_size: 128
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    curriculum: config/curriculum/hunter_curriculum.json
